---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    labels:
      app: "hello-boot"
      version: "0.0.1"
      group: "springdeveloper"
    name: "hello-boot"
  spec:
    ports:
    - name: "http"
      port: 8080
      targetPort: 8080
    selector:
      app: "hello-boot"
      version: "0.0.1"
      group: "springdeveloper"
    type: "LoadBalancer"
- apiVersion: "apps/v1"
  kind: "Deployment"
  metadata:
    labels:
      app: "hello-boot"
      version: "0.0.1"
      group: "springdeveloper"
    name: "hello-boot"
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: "hello-boot"
        version: "0.0.1"
        group: "springdeveloper"
    template:
      metadata:
        labels:
          app: "hello-boot"
          version: "0.0.1"
          group: "springdeveloper"
      spec:
        containers:
        - env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          - name: APP_MESSAGE
            value: Kubernetes
          - name: SPRING_PROFILES_ACTIVE
            value: kubernetes
          image: "springdeveloper/hello-boot:0.0.1"
          imagePullPolicy: "Always"
          name: "hello-boot"
          ports:
          - containerPort: 8080
            name: "http"
            protocol: "TCP"
          livenessProbe:
            httpGet:
              path: "/actuator/health"
              port: 8080
              scheme: "HTTP"
            initialDelaySeconds: 20
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: "/actuator/health"
              port: 8080
              scheme: "HTTP"
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 10
          volumeMounts:
          - name: config
            mountPath: "/config"
            readOnly: true
        volumes:
        - name: config
          secret:
            secretName: hello-boot
            items:
            - key: application.yaml
              path: application.yaml